server:
  port: 8763
spring:
  application:
    name: feign-service-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/